<?php
/**
 * Generated by framework installer - Thu, 06 Oct 2016 11:33:24 +0200
*/
    class Config
    {
	const BASEDNAME	= '/webProject';
	const DBHOST	= 'localhost';
	const DB	= 'csc3123';
	const DBUSER	= 'csc3123';
	const DBPW	= 'ZtxfrhVvfzTMYTq7';
	const SITENAME	= 'webProject';
	const SITEURL	= 'http://webproject.com';
	const SITENOREPLY	= 'noreply@webProject.com';
	const SYSADMIN	= 'barney.nikolich@gmail.com';
	const DBOP	= '=';
	const UPUBLIC	= FALSE;
	const UPRIVATE	= TRUE;

	public static function setup()
	{
	    Web::getinstance()->addheader([
		'Date'			=> gmstrftime('%b %d %Y %H:%M:%S', time()),
		'Window-target'		=> '_top',	# deframes things
		'X-Frame-Options'	=> 'DENY',	# deframes things
		'Content-Language'	=> 'en',
		'Vary'			=> 'Accept-Encoding',
	    ]);
	}
    }
?>